# Python 3.7
# Exceptions / erreurs
# TP by yishan le 31/12/2018

try:
    resultat = numerateur / denominateur
except type_de_l_exception as exception_retournee:
    print("Voici l'erreur :", exception_retournee)